foreign_sched_values_calc: Fix error due to incomplete withholding key.
Fixes the following error:
	Traceback (most recent call last):
	  File "...", line 4858, in <module>
	    sys.exit(main())
	             ~~~~^^
	  File "...", line 4852, in main
	    create_schedule_fsi_and_form_67(avg_tax_rate)
	    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
	  File "...", line 4741, in create_schedule_fsi_and_form_67
	    add_to_form67(*args)
	    ~~~~~~~~~~~~~^^^^^^^
	  File "...", line 4655, in add_to_form67
	    withholding_tax_rate_pc = country_attr("tax_withholding_rate_percent")
	  File "...", line 4652, in country_attr
	    return getattr(country, f"{attr}_{income_type_key}")
	AttributeError: 'Country' object has no attribute 'tax_withholding_rate_percent_dividend'. Did you mean: 'tax_withholding_rate_percent_for_dividend'?

Fixes: 07c305f87fb4 ("foreign_sched_values_calc: Fix form67 values for withholding > dtaa.")
Signed-off-by: Siddh Raman Pant <25429745+siddhpant@users.noreply.github.com>