foreign_sched_values_calc: Add sale_proceeds_in_broker_doc to fix broker rounding in cash ledger.
Broker rounds the money to cents, but we have more precision. This led
to the following error during cash withdrawal:
	ValueError: Debiting amount > balance in the cash wallet (entity FYIXX).

The difference was < 0.01. It happens because we deposit exact cash
whereas broker has mentioned the rounded value. So let's fix that up.

While at it, also fix misconception about cash_fund_switch in example.

Signed-off-by: Siddh Raman Pant <25429745+siddhpant@users.noreply.github.com>